### ISSUE TITLE
Compilation fails.

### ISSUE THREAD

**Issue by ascherer** [rpm-software-management/rpm#608]
Trying to do the following on Kubuntu 16.04.5
```
git clone --depth=1 git@github.com:ascherer/rpm.git
cd rpm
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt update
sudo apt install autoconf-archive fakechroot libarchive-dev:amd64 libdb4.8 libdb4.8++ libdb4.8++-dev libdb4.8-dev libfakechroot:amd64 libltdl-dev:amd64 liblua5.2-0-dbg:amd64 liblua5.2-dev:amd64 libmagic-dev:amd64 libnspr4-dev libnss3-dev:amd64 libperl-dev libpopt-dev:amd64 libreadline-dev:amd64 libreadline6-dev:amd64 libtinfo-dev:amd64 libtool-bin libzstd1 lua5.2 pkg-config quilt zlib1g-dev:amd64 zstd
./autogen.sh --noconfigure
sed "s/lua >=/lua5.2 >=/g" -i configure
./configure
make
```
fails with
```
rpmliblua.c: In function ‘rpmLuaInit’:
rpmliblua.c:39:45: error: ‘LUA_LOADED_TABLE’ undeclared (first use in this function)
     lua_getfield(lua->L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);
                                             ^
rpmliblua.c:39:45: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by ignatenkobrain** [comment]
What version of Lua?

**Comment by ascherer** [comment]
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio

**Comment by ascherer** [comment]
I'll `bisect`: compilation worked at 7ffc4d1 in September (when I submitted my last PR).

**Comment by ascherer** [comment]
f13de84bab9cd5b1be30c44002285743c8c3f7a9 is the first bad commit; see [the associated log files](https://gist.github.com/ascherer/0235fd0c7c16bbe8a03d87eb88c27aeb) for details.

**Comment by ascherer** [comment]
It seems that `"_LOADED"` was replaced by macro `LUA_LOADED_TABLE` in [lua 5.3.4](https://github.com/lua/lua/commit/b2aa2ba046502bdcdfa3de4af898810667c1843a).

**Comment by ascherer** [comment]
Even trying to install `lua5.3` and associated dev stuff in parallel fails, because Ubutun 16.04 only provides Lua 5.3.1 in its standard repos.

**Comment by ascherer** [comment]
It seems [you're at it](https://github.com/rpm-software-management/rpm/pull/169). KYFC!

**Comment by pmatilai** [comment]
Fixed by bcb4781fd8cf91bd558ef22c8c0dfd0915727036, thanks for the report and fix :)
