### ISSUE TITLE
"load" does not work with RPM 4.16.90

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpm#1669]
This issue might be same with #1663 .

* OS: Fedora 35 (rawhide) Linux
* RPM version: 4.16.90-0.git15395.2.fc35

I see the following error started to happen when building ruby on Koji in Fedora project. It seems that the error is related to `load`.

```
DEBUG util.py:444:  error: line 116: Unknown tag: /chroot_tmpdir/srpm_unpacked/SOURCES/macros.ruby
```

https://src.fedoraproject.org/rpms/ruby/blob/rawhide/f/ruby.spec#_116

ruby.spec

```
...
Source4: macros.ruby
...
%{?load:%{SOURCE4}} # <= The error happens on this line 116.
...
```

Here is the dependencies of the ruby.spec. The error did not happen with RPM 4.16.1.3-1.fc35.
https://koschei.fedoraproject.org/build/10236312

Could you tell me how to fix? Is there a temporary workaround to build?
Thanks!

**Comment by junaruga** [comment]
I can try to create a minimal reproducer if you want.

**Comment by pmatilai** [comment]
%{load:...} works as always but any undocumented special behaviors of conditionals on built-in macros are gone in 4.17, %{?foo} always tests whether said macro is defined or not, both built-ins and user-defined macros.

Conditional load can be constructed with more control using expressions and the like, eg
`%[%{exists:/some/file}?"%{load:/some/file}":""]`

**Comment by junaruga** [comment]
Thanks for the info! Let me check it.

**Comment by junaruga** [comment]
Thanks! I confirmed it works with `%{load: ...}`. I would close this ticket.

**Comment by junaruga** [comment]
@pmatilai when using `%{load:...}`, the rpmlint failed to part the spec file. https://github.com/rpm-software-management/rpmlint/issues/632 . The rpmlint can not detect the loaded file's existence.

I see the `%{exists...}` is still new in RPM 4.17. http://rpm.org/user_doc/macros.html
Is there a way to avoid the rpmlnt error?

**Comment by pmatilai** [comment]
Well you can program whatever logic you want if you use %{lua:..}

This behavior isn't changing back.

**Comment by junaruga** [comment]
@pmatilai ok thanks I will try it!

**Comment by junaruga** [comment]
@pmatilai I am seeing `doc/manual/lua.md` and https://rpm.org/user_doc/lua.html . Sorry could you tell me what's wrong in the following code?

```
%load_if_exists(path) %{lua:
  if posix.access(arg.path, "r") then 
    print("Loading " .. arg.path .. "..")
    load(arg.path)
  end  
}

%load_if_exists %{SOURCE4}
```

```
$ fedpkg --release rawhide srpm
error: lua script failed: [string "<lua>"]:2: attempt to index a nil value (global 'arg')
error: query of specfile /home/jaruga/git/pkg/fed/ruby/ruby.spec failed, can't parse
```

**Comment by junaruga** [comment]
> Sorry could you tell me what's wrong in the following code?

I was able to implement the own exists macro like this. I expect `rpmlint` skips the load. But it still checks the load macro printing parsing error. Now what we need to fix is rpmlint.

```
%global exists_file %{lua: posix.access(rpm.expand("%{1}"))}

%if %exists_file "%{SOURCE4}" 
%{echo:loading %{SOURCE4}} 
%{load:%{SOURCE4}}
%endif
```

**Comment by voxik** [comment]
@pmatilai I must say that the error as well as your answer puzzles me. Just FTR, this is the origin of the question mark:

https://src.fedoraproject.org/rpms/ruby/c/8e2921fd5a3125b7ce2487bb449b2e6db40cc3c0

IOW the question mark was always guarding the existence of the `load` macro/builtin.

If I am not mistaken, at that time, the question mark allowed to build at least SRPM via older RPM. What it does ATM is hard to decode, because honestly the error message is quite unexpected and unhelpful.

**Comment by mlschroe** [comment]
Isn't the bug in rpmlint that broke using %{load:} fixed with  https://github.com/rpm-software-management/rpmlint/pull/633 ?

I.e. you can now simply use `%{load:}` instead of the undocumented `%{?load:}`, right?

**Comment by junaruga** [comment]
Yes, the bug in the rpmlint was fixed. For now the `%{load:foo}` is used in `ruby.spec` on the Fedora rawhide (development version) branch instead of `%{?load:foo}`. 

We are asking here to understand more about the details and context.

* "If I am not mistaken, at that time, the question mark allowed to build at least SRPM via older RPM." Did you remember it? Why did you drop it as undocumented feature? I think It's more about a communication between us. 
* "The question mark was useful for backward compatibility."
