### ISSUE TITLE
build/pack.c: build failure due to pragma omp task untied on codesourcery-mips toolchain

### ISSUE THREAD

**Issue by ffontaine** [rpm-software-management/rpm#1420]
We have the following build failure on buildroot with rpm 1.16.0 and codesourcery-mips toolchain (https://sourcery.mentor.com/public/gnu_toolchain/mips-linux-gnu/mips-2016.05-8-mips-linux-gnu-i686-pc-linux-gnu.tar.bz2):

```
pack.c: In function 'packageBinaries':
pack.c:769:26: error: expected '#pragma omp' clause before 'priority'
  #pragma omp task untied priority(i)
                          ^
```

I assume that this build failure is raised since https://github.com/rpm-software-management/rpm/commit/6f6f5e70f16bef21523c3e2f19e7557bfcaa2546 because not all openmp toolchains support `task untied`?

**Comment by dmnks** [comment]
Correct, this is caused by the compiler not supporting some of the OpenMP features (it's actually the `priority` clause). We've added a check into the `configure` script recently to "fix" this: #1325

**Comment by ffontaine** [comment]
Thanks for your answer, unfortunately, commit 6a780f10c2b600cfc38f8b8f20cb7e40b979f541 raises a build failure when cross-compiling because it uses `AC_RUN_IFELSE`. I sent #1431 to fix this issue. Moreover, I would advise to replace AC_MSG_ERROR([OpenMP too old]) by a simple warning that disable openmp. Would it be acceptable?

**Comment by ffontaine** [comment]
I sent #1433, let me know if this is a correct and acceptable solution

**Comment by dmnks** [comment]
This has been resolved by #1455 (as also discussed in #1433), so closing now. Thanks again!
